name: CLI

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MISE_EXPERIMENTAL: "1"

concurrency:
  group: cli-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: jdx/mise-action@v2
      - name: Run build
        run: mise run build
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Auto-build: Update CLI binaries"
            git push
          else
            echo "No changes to commit"
          fi
